### ISSUE TITLE
What license does this use?

### ISSUE THREAD

**Issue by hamishmb** [barracuda156/10A190#2]
Hi there,

This is a really cool project. Is this similar to Darling's SDK in that it's a reimplementation under a proper open-source license, unlike Apple's SDKs?

I want to have some fun with PPC 10.6 soon, so I might have a go with this SDK too.

Hamish

**Comment by barracuda156** [comment]
> Hi there,
> 
> This is a really cool project. Is this similar to Darling's SDK in that it's a reimplementation under a proper open-source license, unlike Apple's SDKs?
> 
> I want to have some fun with PPC 10.6 soon, so I might have a go with this SDK too.

This is an SDK from a Developer build of 10.6, the last one that runs natively on PPC.

It has not been modified.

In practice, some components may indeed be pulled over from:
a) later developer builds (I did that for crt10.6.o from 10A261),
b) releases through 10.6.8 (many components retain ppc slices but have to be tested for compatibility),
c) earlier build of 10.6 for PPC, 10A096, and/or 10.5.8 (relevant for Blutooth and Airport support, for example).

But that a big project and yet to be done.

P. S. I don’t think there is any proper license for this stuff, it’s just old abandonware.

**Comment by hamishmb** [comment]
Okay, sounds complicated!

In that case I feel I can't contribute in terms of looking at or fixing any code, but I should still be able to report issues if I find any.

I'm sure you're right and Apple won't care as this is now 2 architectures behind Apple Silicon, but I work with the Darling developers, at least to some extent, and so don't want to risk any accidental license violation there.

**Comment by barracuda156** [comment]
> Okay, sounds complicated!
> 
> In that case I feel I can't contribute in terms of looking at or fixing any code, but I should still be able to report issues if I find any.
> 
> I'm sure you're right and Apple won't care as this is now 2 architectures behind Apple Silicon, but I work with the Darling developers, at least to some extent, and so don't want to risk any accidental license violation there.

Well, if you refer to OS itself, then many of its components *are* open source, and Apple Open Source website has their source code (mostly for release version but some for developer builds). I think, no Apple OS is 100% open-source though.
Since we don’t have source code for open-source components from 10A190, so there is nothing to look into anyway.

If you install 10A190, you may:
1) test existing open source components from 10.6–10.6.8 (from AOS) within 10A190;
2) build compilers and ports and fix some issues specific to 10.6 PPC and/or Rosetta.

I am working on point 2 myself mostly.
MacRumors and MacintoshGarden have pre-installed images of 10A96 and 10A190, so it is not really complicated to try. My thread about building in Macports has relevant instructions to set that up (credit to @kencu for his help with that, as well as for fixing a number of important ports for 10.6 PPC).

**Comment by hamishmb** [comment]
Yeah, I'd definitely be happy to do #1. Is there somewhere to note what is working and isn't and etc? Or a Discord or Telegram chat or similar so I can ask newbie questions?

That way I can also avoid duplicating other people's work I guess. I'm happy to fix code for AOS stuff yeah, just not for the SDK. I'm mostly a Python developer anyway so it's likely to be a moot point in practice, at least for the moment.

If the compiler's working well enough, I'll be happy to work on #2 in periods where I have some free time to donate to it. I also like documenting things to some extent, so maybe I could contribute something useful to the MacPorts wiki if there isn't already stuff on 10.6 PPC status.

EDIT: Is that thread the one we were just talking on, or a different one?

**Comment by barracuda156** [comment]
@hamishmb Yeah, I meant this thread. Iain has no time to work on 10.6 PPC related issues, so it is better to discuss those elsewhere.
And of those contributing to Macports, I am the only one perhaps working on 10.6 PPC as my main system, at least atm.

Compilers work fine, pretty much like on 10.5.8. There are few ports that fail on 10.5.8 but build on 10.6 PPC and few ports that fail on 10.6 PPC but build on 10.5.8. For the most part fixing something for one system fixes it for another (as long as `ppc32` goes).

I will try to collect today and post here relevant links to installation of 10A190, set up of Macports and needed fixes for few required portfiles and compilers. So that you have everything in one place.

P. S. By the way, if you work with Python, universal builds are broken for ppc+ppc64 for all of them, but especially for pythons 3.x. (This is not relevant to 10.6, but only to 10.5.8.) I have fixed all of them via portfiles (but that is not in Macports base), however if you could find a solution to be implemented in Python source code, that would be far better. (Then PR can be done to Python repo.) The caveat here is that you need G5 hardware for `ppc64`, neither G4 nor Rosetta gonna work.

**Comment by hamishmb** [comment]
Okay, thanks, that'll make it much easier for me to plan and get started :)

Should we make a new issue or something for the links though, or just put them in the readme? You've answered my question about the license so it might make sense to discuss the rest of this stuff somewhere else. EDIT: That's probably what you meant actually, now that I think of it.

Yeah, I might be up for working on a solution for Python universal builds. It'll probably be a while before I have the knowledge for that - I've never really looked into Python internals.

I have a product using Python 2 on PPC from MacPorts, but I can't use Python 3 for it anyway, as wxWidgets for WxPython for Python 3 depends on macOS 10.7+, IIRC. I'm still interested anyway though.

I don't have any G5 hardware, or any space for it, or the money to buy any, so someone else would have to test the ppc64 part of the universal build. I'm sure someone interested enough will show up eventually.

**Comment by hamishmb** [comment]
Actually I might be wrong - wxPython Phoenix does have an older build for Python 2 as well. If that's in MacPorts (or I can add it) that would potentially be useful. As you can imagine, I don't get many customers on PPC, so that's probably going to be mostly for fun, but that's fine.

**Comment by barracuda156** [comment]
> Okay, thanks, that'll make it much easier for me to plan and get started :)

Sounds great.

> Should we make a new issue or something for the links though, or just put them in the readme? You've answered my question about the license so it might make sense to discuss the rest of this stuff somewhere else. EDIT: That's probably what you meant actually, now that I think of it.

Yeah, sure, I will make a separate thread and tag you.

> Yeah, I might be up for working on a solution for Python universal builds. It'll probably be ages before I have the knowledge for that.

In brief, Python source code does not have an option to build ppc+ppc64 (while it does have all sorts of crazy combinations like x86_64+ppc64). For python27 the fix to enable such variant is trivial. For Pythons 3.x it is not.

> I don't have any G5 hardware, or any space for it, or the money to buy any, so someone else would have to test the ppc64 part of the universal build. I'm sure someone interested enough will show up eventually.

I have two PowerMacs G5 and can test everything, no issues. Back to them by end of August (right now only have 10.6.8 Rosetta for ppc).

**Comment by hamishmb** [comment]
Okay cheers, sounds like that will work out :) I'm going to be pretty busy this summer so it's unlikely I'll have done much/anything on this before the end of August anyway, so no problem.

I'll close this issue now then.

**Comment by barracuda156** [comment]
@hamishmb Apologize for a delay, been busy. Getting back to this in coming days (will open a separate discussion thread).

**Comment by hamishmb** [comment]
No problem, same here. Please tag me when you do to make sure I see it :)
